.travis.build.sh, .travis.yml, etl/js/.eslintrc.json, html/.eslintrc.json
- Travis Ci will run the linter on any modifed js or php files. If
there are errors or warnings, then lint will be run on the previous
version of the file. If new errors or warning have been introduced then
the build is in error.
- Also update the lint configuration to match the XDMoD approved
settings.
Improve code quality
Tested by running travis with different code changes that variously fix / break php and javascript code.
=> Enforce new code must have no lint errors or warns

etl/js/config/supremm/etl.schema.js
Add update per bw fixes and ubccr/xdmod#47
=> Fix case off by one

.eslintrc.json, package.json
This pull request applies ubccr/xdmod#67 to this repository.
See ubccr/xdmod#67.
See ubccr/xdmod#67.
=> Updated ESLint and applied new XDMoD rules

build.json
The SUPReMM ETL framework will be included in the Open XDMoD package.
Changes build configuration to no longer include the SUPReMM ETL framework in the Open XDMoD SUPReMM module package.
See ubccr/xdmod#106
What is referred to here as the SUPReMM ETL framework is not specific to SUPReMM and is considered part of the base Open XDMoD package.  Therefore, it should be packaged as such.
Installed Open XDMoD and the SUPReMM module before and after this change.  Compared both installations to ensure that all the same files are installed.  Also compared contents of tarballs before and after the changes to ensure the files were present where expected.
=> Remove SUPReMM ETL framework from Open XDMoD SUPReMM module package

xdmod-supremm.spec.in
=> Update spec file for pre-release builds

build.json, configuration/portal_settings.d/supremm.ini, xdmod-supremm.spec.in
Updates version numbers to 6.6.0.
=> Update version numbers

docs/supremm-upgrade-overview.md, docs/supremm-upgrade.md
=> Update upgrade notes

CHANGELOG.md, xdmod-supremm.spec.in
This pull request updates the change log for the release of version 6.6.0. The release notes are contained in ubccr/xdmod#96. The release notes contain user-friendly lists of changes, whereas the change log contains deeper, more technical notes.
**Please do not merge until dates and notes are finalized.**
Verified file rendered as expected.
=> Added change log for 6.6.0

CHANGELOG.md, classes/DataWarehouse/Query/SUPREMM/JobMetadata.php, composer.json, composer.lock, docs/supremm-upgrade-overview.md, docs/supremm-upgrade.md, etl/js/config/supremm/output_db/modw_supremm.sql, tests/unit_tests/bootstrap.php, tests/unit_tests/lib/DataWarehouse/Query/SUPREMM/JobMetadataTest.php, tests/unit_tests/lib/TestHelpers/mock/JobMetadataWorkaround.php, xdmod-supremm.spec.in
Merges xdmod6.6 into xdmod6.7
File conflicts:
- `build.json`
- `configuration/portal_settings.d/supremm.ini`
- `xdmod-supremm.spec.in`
=> Merge xdmod6.6 into xdmod6.7 (#36, #38, #39, #43, #44)

.travis.yml, CHANGELOG.md, classes/DataWarehouse/Query/SUPREMM/JobMetadata.php, composer.json, composer.lock, docs/supremm-upgrade-overview.md, docs/supremm-upgrade.md, etl/js/config/supremm/output_db/modw_supremm.sql, tests/unit_tests/bootstrap.php, tests/unit_tests/lib/DataWarehouse/Query/SUPREMM/JobMetadataTest.php, tests/unit_tests/lib/TestHelpers/mock/JobMetadataWorkaround.php, xdmod-supremm.spec.in
Merges xdmod6.7 branch into xdmod7.0
Conflicts:
- build.json
- configuration/portal_settings.d/supremm.ini
- package.json
- xdmod-supremm.spec.in
=> Merge xdmod6.7 into xdmod7.0 (#36, #38, #39, #41, #42, #43, #44, #45)

etl/js/config/supremm/output_db/modw_supremm.sql
update sql file to be more like the others and cleanup
Removed create database and use statements to match the rest of the xdmod database files (https://github.com/ubccr/xdmod/blob/xdmod6.7/db/schema/)
and just a bit of cleanup of comments as well as thrasing of variables
This allows the SQL to work with the federation more easily
Verified that the sql still worked on new instances and the database tables were the same.
=> update sql to work with federation / be more in line with others

.travis.install.sh, package-lock.json
See ubccr/xdmod#150.
See ubccr/xdmod#150.
I verified that the main packages pulled in by this module match those pulled in by Open XDMoD, which was confirmed to work.
=> Added npm lock file

.travis.yml, composer.json, composer.lock, tests/artifacts/.gitignore, tests/artifacts/update-artifacts.sh, tests/unit_tests/lib/DataWarehouse/Query/SUPREMM/JobMetadataTest.php, tests/unit_tests/lib/DataWarehouse/Query/SUPREMM/JobTimeseriesTest.php, tests/unit_tests/runtests.sh
See ubccr/xdmod#143.
See ubccr/xdmod#143.
I verified that the unit tests automatically pulled in the artifacts repo and completed successfully.
=> Use Git to manage xdmod-test-artifacts

shippable.yml, tests/integration_tests/lib/REST/Warehouse/JobViewerTest.php, tests/integration_tests/lib/REST/internal_dashboard/DashboardSupremmTest.php, tests/integration_tests/runtests.sh, tests/integration_tests/scripts/bootstrap.sh, tests/integration_tests/scripts/xdmod-setup.tcl
Added the necessary scripts/config to enable automatic integration test running using shippable.
The existing tests were written to run against an XDMoD XSEDE instance. I have made the minimal modifications to these so that the pass against an Open XDMoD instance. I'll be doing another pull request to improve the test coverage for the Open XDMoD instance.
yep
=> Add automatic integration tests using shippable

tests/integration_tests/lib/REST/Warehouse/JobViewerTest.php
Just some incremental improvements in the test coverage.
=> Add a few more tests.

README.md
Add support contact information to readme.
Once this goes in we will swtich off the issues tab in github.
=> Add support contact information to readme.

.travis.install.sh, .travis.yml
remove 5.3.3 from travis builds
=> udpate travis per other repos

CHANGELOG.md, xdmod-supremm.spec.in
This pull request updates the change log for the release of version 7.0.0. The release notes are contained in ubccr/xdmod#226. The release notes contain user-friendly lists of changes, whereas the change log contains deeper, more technical notes.
**Please do not merge until dates and notes are finalized.**
Verified file rendered as expected.
=> Updated release notes and change log for 7.0.0

.travis.build.sh, .travis.install.sh, .travis.yml, docs/supremm-upgrade-overview.md, xdmod-supremm.spec.in
The RPM dependency version is now set to strictly xdmod 7.0 to mitigate
problem with end users upgrading the core and not the supremm module.
=> Update s/w copat matrix & rpm dep version.

docs/supremm-upgrade.md
Adds a note about the changes to `supremm_resources.json`.
=> Add 7.0.0 upgrade notes

CHANGELOG.md, xdmod-supremm.spec.in
This updates the change log/release notes to include some final pull requests for 7.0.0.
I [did a zoom](https://i.imgur.com/MCFP6DV.gifv) and merged the previous pull request for this purpose before we were actually done. Sorry about that and the resulting email spam, all.
- Documentation update
=> Updated 7.0.0 release notes

shippable.yml, tests/automated_tests/.eslintrc.json, tests/automated_tests/test/specs/jobViewer.js, tests/automated_tests/test/specs/jobViewer.page.js
=> Add autotests to the build.

classes/DataWarehouse/Query/SUPREMM/JobMetadata.php, tests/integration_tests/lib/REST/Warehouse/JobViewerTest.php
=> Add pdf export support

composer.json, composer.lock
update php version to 5.4.16 instead of 5.3.3
=> update php version

tests/regression_tests/runtests.sh
make it not break in the wrong way
=> fix test runner to actually wait

composer.json, composer.lock
composer version now matches spec version
=> Make composer match spec

xdmod-supremm.spec.in
=> Update RPM spec file

docs/supremm-upgrade-overview.md
=> Update compatibility table

CHANGELOG.md, docs/supremm-processing-configuration.md, docs/supremm-upgrade.md
=> Update documentation and changelog

configuration/portal_settings.d/supremm.ini, xdmod-supremm.spec.in
=> Release preparations

docs/supremm-configuration.md
acl-config must be run after xdmod-setup
=> Update docs to tell people to run acl-config

classes/OpenXdmod/Setup/SupremmDbSetup.php, tests/integration_tests/scripts/xdmod-setup.tcl
=> Add acl-config call to the database setup menu.

classes/NewRest/Controllers/SupremmDataflowControllerProvider.php, etl/js/config/supremm/etl.schema.js
Companion of ubccr/xdmod#349 and ubccr/xdmod-xsede#81
```
PHPUnit 4.8.23 by Sebastian Bergmann and contributors.
Runtime:	PHP 5.4.16
Configuration:	/root/build/xdmod-supremm/tests/integration_tests/phpunit.xml.dist
........................I..
Time: 7.75 seconds, Memory: 5.25Mb
OK, but incomplete, skipped, or risky tests!
Tests: 27, Assertions: 223, Incomplete: 1.
^[[BCloning xdmod-test-artifacts into local directory...
Cloning into './xdmod-test-artifacts'...
remote: Counting objects: 8018, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 8018 (delta 0), reused 5 (delta 0), pack-reused 8008
Receiving objects: 100% (8018/8018), 1.08 MiB | 4.13 MiB/s, done.
Resolving deltas: 100% (4965/4965), done.
Cloning xdmod-test-artifacts into local directory...
Cloning into …
```
=> Updates required for hpcdb->modw etlv2 migration

background_scripts/aggregate_supremm.php, configuration/etl/etl.d/supremm_realm.json
Add the `"module": "supremm"` to ETL configuration files in support of ubccr/xdmod#577.
=> Add module name to etl pipeline definitions

classes/Rest/Controllers/SupremmDataflowControllerProvider.php, configuration/rest.d/supremm_dataflow.json
=> Rename NewRest to Rest

Dockerfile, shippable.yml
=> Update Docker for Shippable

docs/supremm-compute-pcp.md
Update Installation and Configuration instructions for PCP
Bring the Docs up to date
=> PCP Documentation updates for 8.0

classes/DataWarehouse/Query/SUPREMM/JobDataset.php
Data are stored in the database as a ratio and converted to % for humans to read.
=> Ensure GPU statistics are displayed correctly.

background_scripts/xdmod-supremm-jobinfo
This script has been around for a while- this just updates it for xdmod8.0 and includes it in the build. The script will be referenced in the troubleshooting guide.
=> Add xdmod-supremm-jobinfo helper script to build

classes/DataWarehouse/Query/SUPREMM/SupremmDbInterface.php, tests/integration_tests/lib/REST/internal_dashboard/DashboardSupremmTest.php
The php code was ignoring the enabled flag in the supremm_resources
=> Enusre the enabled setting is honoured

Dockerfile
=> Update docker for working email version

etl/js/config/supremm/output_db/Query/SUPREMM/GroupBys/GroupByNsfdirectorate.php, etl/js/config/supremm/output_db/Query/SUPREMM/GroupBys/GroupByParentscience.php
=> Fix "Group By" joins

etl/js/config/supremm/etl.profile.js
see https://github.com/ubccr/xdmod/pull/712
=> Code changes needed for updated mongo driver

Dockerfile, build.json, xdmod-supremm.spec.in
=> Docker level UP!

configuration/etl/etl.d/supremm_realm.json
changes as a consequence of https://github.com/ubccr/xdmod/pull/742
=> API changes needed for ETLv2 integration

configuration/etl/etl.d/supremm_realm.json
This pul request updates the ETLv2 pipeline to call the autogenerated postprocessing SQL. Also add a gitignore file so the installer includes the appropriate directory.
=> Updates required by https://github.com/ubccr/xdmod/pull/770

shippable.yml
=> Fix shippable file

tests/integration_tests/lib/REST/Warehouse/JobViewerTest.php
This test checks the code path that was fixed in https://github.com/ubccr/xdmod/pull/834
=> Added test to confirm ubccr/xdmod#834

background_scripts/supremm_sharedjobs.php
This change adds the ability to select the resource that is processed
as well as the time range to process.
=> Add more command line config to shared jobs script

background_scripts/supremm_sharedjobs.php
The job peers data was batched up and loaded once (per run). This resulted in very large (hundreds of GB) files and long 'LOAD DATA' times (multiple hours) when processing lot of jobs.  This change means that the job peers data is bulk written in chunks. This improves the performance significantly. In a test the bulk load with ~250,000 row chunks was ten times faster than the single bulk load of similar amount of data.
=> Performance Improvements for shared_jobs script

background_scripts/xdmod-supremm-admin, classes/DataWarehouse/Query/SUPREMM/SupremmDbInterface.php, docs/supremm-install-overview.md, docs/supremm-upgrade.md
=> Add script for administrative tasks

Dockerfile, build.json, shippable.yml, tests/automated_tests/test/specs/jobViewer.js, tests/integration_tests/bootstrap.php, tests/integration_tests/scripts/bootstrap.sh, tests/regression_tests/phpunit.xml.dist, tests/unit_tests/bootstrap.php, xdmod-supremm.spec.in
update teh shippables stuff to work...
=> Updates for new docker image

.travis.yml
Per the title.
Consistency with XDMoD [#959](https://github.com/ubccr/xdmod/pull/959)
=> Add Explicit Distro To Travis

html/gui/js/modules/summary/UserJobEfficiencyPortlet.js
=> Update no data message in UserJobEfficiency portlet

etl/js/config/supremm/etl.schema.js
Add local job id to batch export.
Job id should be in the exported data.
=> Add local job id to batch export

tests/automated_tests/test/specs/jobViewer.js, tests/automated_tests/test/specs/jobViewer.page.js
See pull ubccr/xdmod#1092 for details
=> Add tests to confirm ubcc/xdmod#1092

docs/supremm-processing-configuration.md
The assets directory moved in recent releases of the software.
=> Update the paths to summarization sw assets dir

tests/integration_tests/scripts/bootstrap.sh
Cherry picks: Update Dockerfile and tests bootstrap (#198)
=> Fix upgrade test script

tests/automated_tests/test/specs/jobViewer.js, tests/automated_tests/test/specs/jobViewer.page.js
see https://github.com/ubccr/xdmod/pull/1201
=> Update test artifacts to account for search history ui improvements

classes/DataWarehouse/Query/SUPREMM/RawData.php
add jobname to datawarehouse jobs search
=> Add job name to jobsearch

build.json
exclude tests from the package
=> dont package tests

shippable.yml, tests/regression_tests/runtests.sh
This adds the regression test run script to the shippable build. This will ensure that the regression tests run.
=> Add regression tests to the build

.gitignore, build.json, classes/DataWarehouse/Query/SUPREMM/JobDataset.php, configuration/rawstatistics.d/10_supremm.json, etl/js/config/supremm/etl.schema.js, xdmod-supremm.spec.in
See ubccr/xdmod#1343
~~Tests are expected to fail until changes in `xdmod` are merged.~~ (`xdmod` changes have been merged.)
=> Raw stats supremm refactoring

html/internal_dashboard/supremm/user_check.php
=> Remove legacy code

docs/supremm-processing-configuration.md
Note this is going into the 8.5 documentation and will be merged up into the 9.0 stuff
=> Update documentation about the hostname_mode setting.

etl/js/config/supremm/output_db/groupbys.json
See https://github.com/ubccr/xdmod/pull/1374
=> Remove incorrect additional_join_contraints on the resource groupby

docs/_data/toc.yml, docs/jobefficiency.md
Also update the table of contents to add and 'advanced usage' section
and add the extending.md to it too.
=> Add info about the jobefficiency algorithm.

etl/js/config/supremm/output_db/groupbys.json
=> Add missing GroupBy categories

classes/DataWarehouse/Query/JobEfficiency/RawData.php, classes/DataWarehouse/Query/SUPREMM/RawData.php, classes/Rest/Controllers/SupremmDataflowControllerProvider.php
**Note: https://github.com/ubccr/xdmod/pull/1461 will need to be merged before this PR** 
We are migrating away from the PEAR Log library as it is no longer maintained. We have settled on utilizing the PSR\Log standard w/ Monolog providing the implementation. 
Since PEAR Log is no longer supported, we needed to upgrade our logging structure to prepare for readying Centos8 support. Deciding to use an accepted PSR standard will help insulate our code from further changes later on down the line.
=> Migrating Pear Log => Monolog

.circleci/config.yml, composer.json, tests/regression_tests/runtests.sh
=> Adding base CircleCI config file

docs/supremm-install-pcp.md, docs/supremm-processing-install.md, docs/supremm-processing-upgrade.md
The documentation for PCP dependencies was incorrect.
=> Update some woefully out of date documentation.

html/internal_dashboard/supremm/stats.php
This only directly impacts the internal dashboard data flow diagram. This was tested manually on metrics-dev.
=> Update jquery to 3.6.0 in sync with xdmod core 9.5.1

build.json, classes/Rest/Controllers/EfficiencyControllerProvider.php, configuration/efficiency_analytics.json, configuration/rest.d/efficiency.json, xdmod-supremm.spec.in
This PR configures the EfficiencyControllerProvider that allows for new REST endpoints to be added as needed for the efficiency tab. Includes the efficiency_analytics.json file that stores all information about the analytics that will displayed in the efficiency tab. The new endpoint that is set up in the controller gets information from this file to populate analytics within the tab. 
Tested in docker.
=> Setup Efficiency Controller Provider for adding new REST endpoints related to efficiency tab.

configuration/efficiency_analytics.json, html/gui/css/Efficiency.css, html/gui/js/modules/efficiency/Efficiency.js, html/gui/js/modules/efficiency/ScatterPlotPanel.js
Initial PR for adding the efficiency tab used the wrong statistic for homogeneity. This updates the json file to include correct statistic as well as corrects the titles for charts that use total cpu hours. 
This PR also updates the help text for each analytic. 
Fixes this issue: 
https://app.asana.com/0/1200028182662861/1201687995403799/f
Tested on metrics-dev.
=> Change statistic for homogeneity analytic and update help text for analytics.

tests/integration_tests/lib/REST/Efficiency/EfficiencyTest.php
This test adds tests for checking the scatter plot data and drilldown chart data endpoints which have been added to support the efficiency tab. 
Tested in docker. 
New integration tests.
=> Add integration test for new endpoints in efficiency controller provider. 

docs/_data/toc.yml
Adds new documentation to menu.
See #304
Missing menu item.
=> Add job efficiency customization to menu

docs/supremm-compute-pcp.md
Some improvements to the PCP configuration guide.
=> Update docs related to pcp configuration

tests/integration_tests/scripts/validate.sh
Add quotes to prevent word splitting.  Fix typo. 
The command may return a value containing spaces.  This results in this error:
```
./tests/integration_tests/scripts/validate.sh: line 56: [: too many arguments
```
See https://app.circleci.com/pipelines/github/ubccr/xdmod-supremm/348/workflows/aa6d5204-f756-4fa5-b41b-b2266c52c5b7/jobs/735?invite=true#step-111-5
Ran the script.
=> Fix test and typo

.circleci/config.yml, classes/DataWarehouse/Query/SUPREMM/JobMetadata.php, classes/DataWarehouse/Query/SUPREMM/SupremmDbInterface.php, composer.json, composer.lock, tests/ci/Docker/Dockerfile.centos8, tests/ci/Docker/Dockerfile.centos8.base, tests/ci/Docker/Dockerfile.rockylinux8, tests/ci/Docker/Dockerfile.rockylinux8.base, tests/integration_tests/lib/REST/Warehouse/JobViewerTest.php, xdmod-supremm.spec.in
These changes make it so that xdmod-supremm can be run on PHP7.2+
It's good to move with the times.
=> Centos8 changes

classes/Rest/Controllers/SupremmDataflowControllerProvider.php, tests/integration_tests/lib/REST/SupremmDataflow/QualityTest.php
Created new REST endpoint at **/rest/supremm_dataflow/quality** with mandatory parameters **start**,  **end**, and **type**.
- **start** and **end** parameters represent desired start and end dates of requested data in YYYY-MM-DD format.
- **type** parameter represents the requested SUPReMM job data. Valid type arguments are: 
- **gpu** for % of CCR SUPReMM jobs with GPU information
- **hardware** for  % of CCR SUPReMM jobs with hardware perf information
- **cpu** for % of CCR SUPReMM jobs with cpu usage information
- **script** for % of CCR SUPReMM jobs with Job Batch Script information
- **realms** for % of CCR jobs in the SUPReMM realm compared to Jobs realm
Data not accessible to public users.
Functionality was adapted from `supremm_quality.php`, which had been sending daily SUPReMM …
=> Created SUPReMM Quality REST Endpoint

.circleci/config.yml
Needed for compatibility with changes in https://github.com/ubccr/xdmod/pull/1675
=> Update ci scripts to accommodate the changes to composer config filename

CHANGELOG.md, build.json, configuration/portal_settings.d/supremm.ini, docs/_config.yml, xdmod-supremm.spec.in
Update version numbers to 10.0.1
=> Release prep.

docs/_config.yml, docs/analytics.md, docs/supremm-compute-pcp.md, docs/supremm-install-pcp.md
=> More pcp docs

CHANGELOG.md, classes/OpenXdmod/Setup/SupremmResourcesSetup.php, configuration/portal_settings.d/supremm.ini
Also fix the bug in the default dataset mapping name that should have been in #346
=> Update changelog for 10.5 release

.circleci/config.yml
Same as https://github.com/ubccr/xdmod/pull/1733/ but for `xdmod-supremm`.
=> Catch PHP command-line errors in CircleCI.

_config.yml
Same as https://github.com/ubccr/xdmod/pull/1811 for `xdmod-supremm` website.
This PR also fixes the missing version number in the banner on the unsupported version pages.
=> Update list of supported versions on website.

etl/js/config/supremm/etl.schema.js, etl/js/config/supremm/output_db/groupbys.json, tests/integration/lib/Controllers/UserInterfaceControllerTest.php, tests/integration/lib/REST/Warehouse/JobViewerTest.php
For some reason this groupby was missing. Added in now.
=> Add GPU Count group by

README.md
This PR adds a reference to the README for the XDMoD paper.
=>  Add citation for the XDMoD paper.

build.json
=> Bumping for 11.0 rc.1

configuration/portal_settings.d/supremm.ini
Update version number so we can make release candidate files.
=> Update version number for XDMoD 11.0.0

etl/js/config/supremm/etl.schema.js, etl/js/config/supremm/output_db/groupbys.json
=> Fixed minor spelling and grammar errors

build.json
=> Update `build.json` for new release candidate

docs/supremm-upgrade.md
This PR also makes reference to a documentation change from https://github.com/ubccr/xdmod-supremm/pull/378 that needs to be merged concurrently.
=> Add 11.0 upgrade notes.

build.json, xdmod-supremm.spec.in
Update `xdmod-supremm.spec.in` and `build.json` files for xdmod-supremm 11.0.0 release
=> Update `spec.in` and `build.json` for 11.0 release

CHANGELOG.md, docs/supremm-install-overview.md, docs/supremm-install-pcp.md, docs/supremm-install.md, docs/supremm-processing-configuration.md, docs/supremm-processing-install.md, docs/supremm-processing-upgrade.md
Port of https://github.com/ubccr/xdmod-supremm/pull/418 for the `main` branch.
=> Update docs to remove CentOS 7.

CHANGELOG.md, build.json, configuration/portal_settings.d/supremm.ini, docs/_config.yml, docs/supremm-upgrade.md, xdmod-supremm.spec.in
_Note: CentOS 7 tests expected to fail._
Updates for compatibility, see also https://github.com/ubccr/xdmod/pull/1971
=> Prepare for v10.5.1 release.

docs/supremm-install.md, docs/supremm-processing-install.md
The installation instructions to enable the PowerTools repository required for the python summarization tools were missing. This PR adds the command to enable the PowerTools repository. The corresponding documentation PR's are here:
* [11.0](https://github.com/ubccr/xdmod-supremm/pull/408)
* [10.5](https://github.com/ubccr/xdmod-supremm/pull/407)
=> Update incomplete installation instructions
