ubccr/xdmod-supremm

CHANGELOG.md
docs/supremm-upgrade.md
xdmod-supremm.spec.in

Since v6.5.0 moves a dependency into npm, this dependency needs to be installed on upgrade. This happens naturally as part of source upgrades, but not as part of RPM upgrades. This pull request makes it clear what needs to be done to get an RPM install back up and running.
In a future Open XDMoD release, npm dependencies will be included with packages and their setup will be better automated.
Checked that Markdown was valid.

Added documentation for updating npm dependencies after updating via RPM

---

bin/aggregate_supremm.sh

Add support for a debug cmdline flag.
Adds a -d flag to call all subprocesses with the debug log on.
Used for debugging
This code has been running on BW for the past few months without problems.
- New feature (non-breaking change which adds functionality)
- My code follows the code style of this project as found in the **CONTRIBUTING** document.
- All new and existing tests passed.

Add support for a debug cmdline flag.

---

.travis.build.sh
phpcs.xml

- Make sure phpcs settings are the same
- Make sure new files are checked in travis.
Created some test commits and additions and ran in travis.

Synchronise the CI setup with the XDMoD core.

---

classes/DataWarehouse/Query/SUPREMM/JobTimeseries.php
composer.json
composer.lock
tests/bootstrap.php
tests/lib/DataWarehouse/Query/SUPREMM/JobTimeseriesTest.php

- The timeseries docs allow individual metrics to be absent and report
and error code. The php code did not check for the error code and incorrectly
assumed that the data was present.
- Added unit test to confirm that the code change worked.
Note also added the xdmod-test-artifacts as a dependency for the test data needed
by the unit test.
Also removed a spurious debug print statement from the test harness.
Bug fix
Ran unit tests

Fix job viewer load error with version 4 timeseries documents.

---

composer.json
composer.lock

Update lock file with php-codesniffer dependency stuck to a specific version, bring all repositories in line with same version
Make sure all composer.lock files match composer 1.3.x version
ran composer install without errors.

update composer and php-codesniffer dep

---

.travis.build.sh
.travis.yml

This pull request modifies the behavior of the Travis cache mechanism to cache npm's global cache directory instead of `node_modules` directories.
If accepted, similar pull requests will be opened for other XDMoD repos.
Unexpected behavior is more likely to occur when copying and updating an old `node_modules` directory than when creating a fresh `node_modules` directory, as evidenced by the Travis errors encountered with #28. This change ensures that fresh `node_modules` directories are created each run while still allowing us to benefit from the Travis cache mechanism.
Ran test runs of Travis with the changes and verified that they completed successfully.

Travis: Cache npm cache directory instead of node_modules directories

---

etl/js/config/supremm/output_db/modw_supremm.sql

The table definition change was incorrectly ommitted from pull request #27.
This change adds the missing definitions.
compared the table definition with the mysqldump of a correctly migrated datawarehouse instance.
-  Bug fix (non-breaking change which fixes an issue)

Fix issue with missing table definition.

---

classes/DataWarehouse/Query/SUPREMM/JobMetadata.php
composer.json
composer.lock
tests/unit_tests/bootstrap.php
tests/unit_tests/lib/DataWarehouse/Query/SUPREMM/JobMetadataTest.php
tests/unit_tests/lib/TestHelpers/mock/JobMetadataWorkaround.php

Fix php error when processing job summaries that had a wildcard schema entry, but the
corresponding summary entry was marked as error.
Also add unit tests for the code change. Now have 100% code coverage for
the function.
Bug fix
Created and ran unit tests.
-  Bug fix (non-breaking change which fixes an issue)

Fix error when processing job summaries that are marked as error.

---

classes/DataWarehouse/Query/SUPREMM/JobDataset.php

The job peers framework code needs the job start and end times
for all jobs. This change ensures that these values are pulled from the
database.
Also add an order by clause to the peers query so that jobs are returned
in time order.

Ensure JobDataset provides the required data fields.

---

.eslintrc.json
classes/DataWarehouse/Query/SUPREMM/SupremmDbInterface.php
classes/OpenXdmod/Setup/SupremmEditResourceSetup.php
classes/OpenXdmod/Setup/SupremmResourcesSetup.php
configuration/supremm_resources.json
docs/supremm-configuration.md
etl/js/config/supremm/etl.profile.js
tests/integration_tests/scripts/xdmod-setup.tcl

The configuration setting for the mongo collection has caused no end of
support requests with folks setting the wrong value. This pull request
removes this setting from view. The setting is now optional and, if
absent, the code uses a sensible default.

Remove collection configuration option.

---

classes/DataWarehouse/Query/SUPREMM/SupremmDbInterface.php
classes/NewRest/Controllers/SupremmDataflowControllerProvider.php
configuration/internal_dashboard.d/supremm.json
html/internal_dashboard/supremm/css/style.css
html/internal_dashboard/supremm/js/stats.js
html/internal_dashboard/supremm/stats.php

- Update diagram to show Open XDMoD dataflow.
- Change orientation to resemble the dataflow diagram in the main documentation for consistency.
- All configured resources are now shown in the drop down rather than just the ones that have data in the datawarehouse.
This page is intended to be used to help the support team diagnose problems with SUPReMM installs. Hopefully savvy users will be able to diagnose the source of problems themselves without our help.
Installed this on metrics-dev and confirmed the page displays correctly in Firefox Linux, Chrome Linux, Firefox OSX and Chrome OSX

Enable dataflow diagram by default.

---

build.json
xdmod-supremm.spec.in

- Added modules.d/supremm.json to the file_maps section of build.json
Added the modules.d/supremm.json file to build.json so that it is included in the packaged module.
Needed to pipe through the new modules.d/\<module\>.json file through to the package / final installed source. 
Manually tested: 
- Made changes to build.json
- Executed: <xdmod_dir>/open_xdmod/build_package.php --module supremm --skip-assets --verbose
- cd <xdmod_dir>/open_xdmod/build
- tar xvzf xdmod-supremm-6.7.0.tar.gz 
- ls -alh xdmod-supremm/configuration/modules.d
- ensure that: supremm.json is present
- cat xdmod-supremm/configuration/modules.d/supremm.json
- ensure that the file is a valid json file and contains the correct information.

Added SUPREMM Modules files to build.json

---

docs/supremm-compute-pcp.md

The PCP RPM install puts a file in /etc/pcp/pmlogger/control.d
Need to delete this so pmlogger doesn't try to start multiple
loggers.
The PCP RPM install puts a file in /etc/pcp/pmlogger/control.d
Need to delete this so pmlogger doesn't try to start multiple
loggers.
Documentation fix
None

Update the PCP install documentation

---

db/migrations/7.5.0-8.0.0/modw_supremm.sql

Fix two bugs: 
- When the last_modified column is added the rows get a value of '0000-00-00T00:00' which cannot be converted to a posix timestamp. This means that the etl.log table gets a null in the max_index column and results in a full re-aggregation.
- Add the modw_aggregates.supremmfact_by_day table to the log to prevent a full regeneration of the joblist table.

Update migration script

---

classes/DataWarehouse/Query/SUPREMM/JobDataset.php
tests/automated_tests/test/specs/jobViewer.page.js

The jobviewer has been changed to automatically display the first 4 analytics. This change modifies
the anayltics send to the job viewer to only send the ones that have been vetted.

Only send confirmed analytics data

---

etl/js/config/supremm/dataset_maps/pcp.js

The dataset mapping now correctly maps the error types from the PCP summary API to the XDMoD API for the catastrophe metric.

Improve error handling for catastrophe metric

---

classes/DataWarehouse/Query/SUPREMM/JobMetadata.php

Updated the calling of the the `query->setMultipleRoleParameters` to now provide an XDUser parameter for the currently logged in user.
This function now requires an XDUser parameter be provided. This supports the changes made in https://github.com/ubccr/xdmod/pull/572

Updating setMultipleRoleParameter Usage

---

etl/js/config/supremm/etl.schema.js
tests/integration_tests/lib/REST/Warehouse/JobViewerTest.php

The Grant Type dimension is not used in Open XDMoD at the moment. This change hides it from the UI.
Also added tests that check that all dimensions have values associated (and of course that the Grant Type dimension is no longer present).

Remove Grant Type from the UI

---

bin/aggregate_supremm.sh

The default memory limit for nodejs is not large enough when running a large ingest (~million jobs). Bump the heap limit to 4G
Tested on metrics-dev and metrics-staging.

Added max-old-space-size flag to nodejs args

---

etl/js/config/supremm/etl.schema.js
tests/integration_tests/lib/REST/Warehouse/JobViewerTest.php

These GPU stats and group bys were developed for the BlueWaters workload analysis. This pul request includes them by default for the Open Source release

Add GPU stats from BlueWaters

---

build.json
classes/DataWarehouse/Query/SUPREMM/JobDataset.php
classes/DataWarehouse/Query/SUPREMM/JobMetadata.php
configuration/portal_settings.d/supremm.ini
configuration/rawstatistics.d/10_supremm.json
configuration/rawstatistics.d/supremm.json
templates/portal_settings.template
xdmod-supremm.spec.in

Necessary changes for the Job Viewer API updates:
- remove singlejobviewer setting from portal_settings
- add numeric prefix to the rawstatistics.d config file
- JobMetadata inherits from the interface class
- JobDataset uses new API.

Update the module for the new Job Viewer internal API

---

Dockerfile
tests/integration_tests/scripts/bootstrap.sh

update docker to have reccomended version of mongo installed specifically (3.4.18) from https://docs.mongodb.com/manual/tutorial/install-mongodb-on-red-hat/ instead of from base repos

docker Power Up!

---

db/migrations/8.0.0-8.1.0/modw_supremm.sql
etl/js/config/supremm/etl.schema.js
etl/js/config/supremm/output_db/modw_supremm.sql
etl/js/config/supremm/output_db/supremm_reset.sql

The jobstatus table is not used as of the 8.0.0 release, but it
was incorrectly still being created on a fresh install. This change
fully removes the jobstatus table.

Remove last traces of the jobstatus table.

---

classes/DataWarehouse/Query/SUPREMM/JobDataset.php
classes/DataWarehouse/Query/SUPREMM/SupremmDbInterface.php

_**This commit depends on https://github.com/ubccr/xdmod/pull/806 and should not be merged until it has
been.**_
This commit will ensure that the SUPREMM module no longer uses the
`Xdmod\Config` class. This is part of the Configuration code consolidation
effort.
No need to have two code paths for working with configuration code. 
Manual Testing on xdmod-dev

Replace `Config` usage

---

configuration/rawstatistics.d/10_supremm.json

The new `Configuration` class requires that the type of merged values to be the
same. It is also desirable that the order in which entries in the `realms`
property retain the order in which they are read / processed. To this end the
`realms` value has been changed to an array in the base config file. This commit
propagates that change to its local config file.
So that it plays nice w/ the newly updated rawstatistics.json base file in xdmod
Manual Testing via xsede docker && xdmod-dev port.

Updating the format of rawstatistics local config

---

classes/DataWarehouse/Query/SUPREMM/JobDataset.php
classes/DataWarehouse/Query/SUPREMM/SupremmDbInterface.php

Utilizing the new helper function `assocArrayFactory` to reduce boilerplate.
**NOTE** Requires https://github.com/ubccr/xdmod/pull/818 
Less code === good
Manual Tests on an xsede docker && on xdmod-dev

Removing Configuration boilerplate

---

background_scripts/supremm_sharedjobs.php
configuration/etl/etl.d/supremm-migration-8_0_0-8_1_0.json
configuration/etl/etl.d/supremm_realm.json
configuration/etl/etl_sql.d/supremm/migration-8_0_0-8_1_0.sql
configuration/etl/etl_tables.d/supremm/jobhost.json
etl/js/config/supremm/etl.schema.js
etl/js/config/supremm/output_db/modw_supremm.sql
tests/integration_tests/scripts/bootstrap.sh
tests/integration_tests/scripts/validate.sh

The jobhost table did not include all of the columns needed to uniquely identify a job (in general). This update makes sure that the unique constraints on this table match the jobs table.
This change moves the jobhosts table management over to etlv2. 
This is a problem for resources that have multiple jobs with the same local_job_id  and have shared jobs. It could result in a incorrect job share mode value being set on a job.

Add end_time_ts column to jobhost table 

---

etl/js/config/supremm/dataset_maps/pcp.js
etl/js/config/supremm/tests/pcp/expected/5659085-1469572318.json

The dateset mapping for infiniband metrics will now use the first infiniband device
in the summary record for data. Previously it hardcoded a specific device name (which
only existed on a subset of nodes at CCR).

Update mapping for InfiniBand metrics.

---

background_scripts/aggregate_supremm.php
classes/OpenXdmod/Setup/SupremmDbSetup.php

The `Configuration` and child classes now require objects be instantiated using one of the `factory()` methods rather than `new Configuration()`.

Update EtlConfiguration to use factory()

---

tests/integration_tests/runtests.sh

Need to run some of the base XDMoD integration tests to ensure the state of the system is correct for subsequent tests.

Run base xdmod integration tests

---

classes/DataWarehouse/Query/SUPREMM/RawData.php

This ensures that the results of the advanced search and the recent jobs portlet are ordered
in time and the paging works as expected.

Add order by end_time to RawData

---

tests/integration_tests/scripts/xdmod-setup.tcl

The DataWArehouse Export feature added a new menu item to `xdmod-setup`. This means that the SUPREMM menu is pushed down one.

The supremm menu is now option 9.

---

configuration/datawarehouse.d/jobefficiency.json
tests/integration_tests/lib/Controllers/MetricExplorerControllerTest.php
tests/integration_tests/lib/Controllers/UserInterfaceControllerTest.php
tests/integration_tests/lib/REST/Warehouse/DataTest.php

Update the config for the JobEfficiencty realm so that it is not shown in the catalog and add tests to confirm that it is not available to the Metric or Usage tabs and is available to the data access rest endpoints.
This pull request depends on ubccr/xdmod#1047

Ensure JobEfficiency realm is not shown in metric catalog

---

background_scripts/aggregate_supremm.php

The optimize table step on the XSEDE machines takes tens of minutes due to the size of the tables.
When the optimize is running the user interface is unusable.
This change adds the ability to switch off the optimise step on the command line.
The cron scripts on xsede prod and dev will be updated to only run the optimize tables once a week on the weekend. This will ensure that the tables are still periodically analyzed, but will significantly reduce the impact on the front end.

Add option to agg script to configure optimise table

---

background_scripts/aggregate_supremm.php

This pull request cherry picks the analyize tables flag commit into the 8.6 branch. This is needed for the XSEDE 8.6 release.

Add option to agg script to configure optimise table (backport to 8.6)

---

classes/DataWarehouse/Query/JobEfficiency/GroupBys/GroupByProvider.php
configuration/datawarehouse.d/jobefficiency.json

The Provider group by is needed so that users with center staff and
center director role can see the efficiency report for jobs from their
center in the XSEDE version.
The absence of this group by was not a problem for the open source version because there is only a single provider

Add GroupByProvider.

---

shippable.yml

turns off the composer warning about running as root, since we know we are doing this for a reason.

composer quit being so annoying

---

.travis.yml
shippable.yml

The XDMOD_REALMS environment variable became mandatory as of
https://github.com/ubccr/xdmod/pull/1261

Add XDMOD_REALMS environment variable to build.

---

etl/js/config/supremm/output_db/groupbys.json
tests/artifacts/regression/chartFilterTests.json
tests/regression_tests/bootstrap.php
tests/regression_tests/lib/Controllers/MetricExplorerSupremmChartsTest.php
tests/regression_tests/phpunit.xml.dist
tests/regression_tests/runtests.sh

This regression tests check that the chart filters work correctly. The test values were created with the 8.5 release of the software.
The test framework has been updated so that the linker pulls in the base test classes and the test class has been created that overrides the provide to provide the supremm tests.

Add tests to check chart filters work in SUPReMM realm.

---

docs/_data/toc.yml
docs/supremm-jobscript.md
docs/supremm-processing-configuration.md

This is the same documentation as #222 backported to the 8.5 version of the software

Add job script documentation for 8.5

---

html/gui/js/modules/dashboard/UserJobEfficiencyComponent.js

The new groupby refactor code requires all statistics to be explictly
specified. Previously there were a set of default stats that were added
automatically.
This change updates the component so all needed stats are explicitly
requested.

Fix regression caused by groupby refactor changes

---

classes/DataWarehouse/Query/JobEfficiency/RawData.php
configuration/datawarehouse.d/ref/job-efficiency-group-bys.json
configuration/etl/etl_action_defs.d/jobefficiency/jobefficiency_by.json
configuration/etl/etl_action_defs.d/jobefficiency/jobefficiency_by_day.json
docs/supremm-upgrade.md
html/gui/js/modules/dashboard/JobEfficiencyComponent.js

Clicking on a person/pi in the job efficiency component
now brings up a window that lists the jobs that were classified
as inefficient for the person/pi.
While implementing this feature two seperate bugs were found:
1) The aggregation query erronously omitted the job_category_id from the group by
leading to incorrect values in the job_category_id column
2) The new json config in the group-by refactor had the wrong table name for the
category groupby
these two bugs are fixed in this pull request because you need the changes
in this pull request to be able to confirm that the fixes work.
fixed at the same time since there was previously noway to test the bug
**This pull request depends on https://github.com/ubccr/xdmod/pull/1283 being merged.**

Add drilldown to jobs for the JobEfficiency component.

---

tests/automated_tests/test/specs/jobViewer.page.js

We periodically get UI test failures. The most recent was the nightly
build failing due to timeouts clicking on the job in the tree.
requires #235 to pass

Improve test robustness

---

etl/js/config/supremm/output_db/groupbys.json

The original code used the id value to sort the exit status filters.
Since the exit status is added to dynamically as value are ingested this
means that the sort order can vary between xdmod instances.
This changes it to use the name of the exit status so that the filter
order is determined by the sql collation.

Make display of "Exit Status" filters deterministic.

---

html/gui/js/modules/dashboard/UserJobEfficiencyComponent.js

This requires https://github.com/ubccr/xdmod-supremm/pull/230 to be
merged first. Uses same mechanism as the #230 also added bonus is that
the efficient and inefficient jobs are viewable. The search parameters
are set by which dataset is clicked on in the chart.

Enable drill down on the user job efficiency report.

---

tests/automated_tests/test/specs/jobViewer.page.js

More places in the code where waitAndClick is replaced by
waitUntilAnimEndAndClick.
I think the reason why this stuff is failing is the addition of the Jobs node to the tree means that it takes slightly longer to render. We got away without the 'animEnd' restriction before because the tree rendered fast enough. This is a guess though.

More robustness for ui tests.

---

configuration/datawarehouse.d/ref/job-efficiency-group-bys.json
etl/js/config/supremm/output_db/groupbys.json

remove the `attribute_table` as it is not needed after https://github.com/ubccr/xdmod/pull/1288
This will fail until that is merged
This also formats according to "standards" by having 4 spaces and orders the keys alphabetically

Remove unneeded keys, format consistency with xdmod

---

classes/DataWarehouse/Query/SUPREMM/RawData.php

Open OnDemand asked for the ability to show `job_name` this adds it.  This was originally in `8.7` this brings it in to 9.0.

OOD added job_name

---

bin/aggregate_supremm.sh

The job performance data aggregation step runs the mysql analyze tables
command by default after aggregation. This command can take a long time
to run and the XDMoD user interface is unavailable while the commmand is
running. This change updates the top level aggregate_supremm.sh to add
a command line flag to disable the analyze table step.
It is recommended that the analyze tables command should be run periodically
but does not need to be run every day. At CCR the anaylze tables step is run
once per week on a weekend day.

Add ability to disable the analyze table step from the aggregate_supremm.sh script

---

etl/js/config/supremm/etl.profile.js

The configuration settings style being used here is deprecated.
This change updates the config settings to the new style so that
the deperecation warning message is not printed.

Update driver configuration settings for newer driver.

---

configuration/etl/etl.d/supremm-migration-9_5_0-10_0_0.json
docs/supremm-upgrade.md
etl/js/.eslintrc.json
etl/js/config/supremm/dataset_maps/pcp.js
etl/js/config/supremm/etl.schema.js
tests/integration_tests/lib/Controllers/UserInterfaceControllerTest.php
tests/integration_tests/lib/REST/Warehouse/JobViewerTest.php
tests/integration_tests/scripts/validate.sh

Add extra GPU groupby and statistics. This adds:
- GPU Hours Active: Total
- GPU Hours: Total
statistics and "GPU Active" group by. These use the total GPU time / utilization for the job (c.f. the other GPU metrics that default to just GPU device 0).

Add GPU information.

---

classes/DB/EtlJournalHelper.php

If the ingest or aggregation step takes a long time then the database
connection in the Journal Helper times out and the journal entry
does not get written.
This change explicity closes the database connection after each read/write.
The code will automatically open a new connection when needed. The other
possible change would have been to catch the server-has-gone-away exception and
retry (which is what I've done for the logger).  In this case the usage pattern
is well known: the helper needs to access the database once at the start and
once at the end and not in the middle so there is no need to keep an idle
connection open.
This was tested by changing the `/etc/my.cnf.d/server.cnf` file in a
docker instance and adding the following:
```ini
wait_timeout = 30
```
I then put a `sleep(60)` …

Handle case where ingest/aggregation takes a long time and DB conn timeout.

---

etl/js/config/supremm/etl.schema.js

This is a redo of #284 on the xdmod 10.0 branch.
There is a missing where condition on the lookup that matches a job in the supremm realm to the jobs realm. In the event that job identifiers get reused by the resource manager and there is more than one job with the same job identifier then the information about the job in the supremm realm may be incorrectly mapped to the wrong job (with the same identifier) but that ran at a different time.

Add the end_time of the job to the lookup for tg_job_id

---

.circleci/config.yml
tests/ci/scripts/install_dependencies.sh
xdmod-supremm.spec.in

This changes the RPM dependencies to require nodejs 16 and removes
npm as a dependency (npm is packaged up in the nodesource rpm for
nodejs and also I'm not sure that we even need it!).
Added an extra script for the CI build to make sure the docker
is updated with the correct dependency.

Update version of nodejs to the current LTS.

---

.circleci/config.yml

This must have been accidentally missed when we switched to circleCI

Fix list of realms to test.

---

html/gui/js/modules/efficiency/AnalyticPanel.js
html/gui/js/modules/efficiency/ScatterPlotPanel.js

This change removes the unused white space to the left of the charts in the efficiency tab. 
Fixes this issue: 
https://app.asana.com/0/1200028182662861/1201687182483670/f
Tested on metrics-dev.

Change sizing of scatter and drill down charts in efficiency tab.

---

.circleci/config.yml

The default timout for files in the composer file cache is 180 days.
Its been a while since we updated some of these dependencies so
composer has been ageing them out and re-downloading. We noticed
that this was happening because there was a seperate issue with
downloading the highcharts dependency files.
This change increases the composer cache timeout so that the cached
files are perferred. This will (slightly) improve the build times
and works-around the (hopefully temporary) problem with the highcharts
download.

Increase composer file cache timeout

---

classes/Rest/Controllers/EfficiencyControllerProvider.php

Current endpoint only returns data for analytics that are in the configuration file presently. Updated to an if statement rather than a switch statement so by default scatter plot data is returned for any analytics added to the configuration file. 
Change was tested on metrics-dev.

Fixed bug with scatter plot data endpoint to return data if new analytics are added. 

---

html/gui/js/modules/efficiency/Efficiency.js

Updated default duration in efficiency tab toolbar from previous month to 30 days. 
This fixes issue: 
https://app.asana.com/0/1200028182662861/1201687182483692/f
Tested change on metrics-dev.

Change the default duration for efficiency tab toolbar.

---

classes/Rest/Controllers/EfficiencyControllerProvider.php
html/gui/js/modules/efficiency/ScatterPlotPanel.js

This fixes two bugs related to the tooltips not displaying correctly on efficiency tab charts. One fix includes adding code that returns the correct label string to be used for the categories in the drill down histogram plot. The other fix updates the tooltip positioner on the scatter plot so that the entire tooltip is visible for each point in the plot. 
Fixes these issues: 
https://app.asana.com/0/1200028182662861/1201689083643968/f
https://app.asana.com/0/1200028182662861/1201687995403781/f
Tested on metrics-dev.

Fixes bugs with tooltip display on charts in efficiency tab.

---

etl/js/config/supremm/etl.schema.js

Change the interval from (min, max] to [min, max)
Observed because 0% was put in the N/A bin instead of the <10 bin.

Fix comparison in GPU percentage bins.

---

docs/supremm-install.md
tests/ci/scripts/install_dependencies.sh
xdmod-supremm.spec.in

Revert CI build to use the EPEL version of nodejs. Note the previous
RPM had a runtime dependency on npm. This is not actually needed it
is really a build time dependency. The spec file has been updated to
fix this.
Also update the version number in the markdown (should have been done
earlier).

Update rpm deps and docs for nodejs EPEL version.

---

html/gui/js/modules/efficiency/Efficiency.js
html/gui/js/modules/efficiency/FilterPanel.js

Some filter checkboxes shared ids which caused issues with how filters were populating in the filter menus. Fixed by giving each checkbox a unique id by specifying dimension name in the id field. Filter checkboxes are removed and new checkboxes are populated when navigating between different analytic views, so no ids are being shared in this way.
Filters were not being applied when they were checked if the filter was hidden in the menu. Filters were staying checked due to event handler not being removed after firing event. Set all handlers for showing/more less filter buttons to single and created a new object to store which filters have been checked. Now using that object to apply filters and recheck as needed on showing more or less filters in the menu.  
Fixes issues: …

Fix bugs with filtering menu in efficiency tab. 

---

html/gui/js/modules/efficiency/ScatterPlotPanel.js

The analytic for memory usage was changed from "memory headroom" to "memory usage", but associated change for adding a unique column on memory usage drill down to job list was not made. This change uses the correct term for memory usage in the switch statement when creating a unique column for a specific analytic and updates the default statement to hide the column if analytic is not included in any of the cases for the switch statement. Previous default statement was throwing an error when trying to construct the column to be added to the job list table. Now column is constructed as expected and hidden if no analytic is found in the case statements. 
Fixes bug with this error ```Uncaught TypeError: Cannot read properties of undefined (reading 'id')``` being thrown when trying to view job …

Changed default for unique column for memory usage job list drilldown. 

---

html/gui/js/modules/efficiency/Efficiency.js
html/gui/js/modules/efficiency/ScatterPlotPanel.js

Due to bug with getting max x-axis value in the getMax function in Efficiency.js, any time the returned data for the restricted data had a value of 0 for the x-axis statistic the x-axis max value would return as NaN causing the scatter plot in the analytic cards to not show all of the correct data. 
Bug fix for displaying scatter plots in analytic cards. 
Changed added to metrics-dev for testing.

Add value for max x-axis when restricted data for x-axis has value of 0. 

---

docs/analytics.md

Images in efficiency tab customization documentation were not sized properly and were too large for page. This resizes all images to fit within the documentation.  
Documentation added with https://github.com/ubccr/xdmod-supremm/pull/304.
Fixes image sizing so images fit within documentation page without overflowing.

Updated image sizing for job efficiency tab customization docs.

---

docs/_config.yml
docs/supremm-compute-pcp.md
docs/supremm-install-pcp.md

Documentation updates to match the template changes in supremm-1.4.2 and to clarify the PCP configuration instructions.
See https://github.com/ubccr/supremm/pull/255 for the corresponding changes associated with these doc updates.

Update documentation for supremm 1.4.2 build

---

classes/Rest/Controllers/SupremmDataflowControllerProvider.php

- Modified query strings to return info on available jobs and total jobs together, rather than the percentage.
- Removed hardcoded columns in GPU query
- The precise values for available and total jobs conveys more information than just percentage.
- Hardcoded columns in GPU query only applied to CCR systems, had to remove them for generality.
Tested various date ranges on every type on my metrics-dev port to make sure response was valid.

Modify SUPReMM Dataflow REST Endpoint

---

tests/automated_tests/test/specs/jobViewer.page.js

Update the Xpath selectors for Plotly timeseries chart titles inside of `jobViewer.page.js`.

Update xpath for chart title

---

build.json
etl/js/config/supremm/tests/pcp/expected/4655275-1445928790.json
etl/js/config/supremm/tests/pcp/expected/4843309-1546457856.json
etl/js/config/supremm/tests/pcp/expected/5659085-1469572318.json
etl/js/config/supremm/tests/pcp/expected/719452-1470861674.json
etl/js/config/supremm/tests/pcp/expected/8291026-1518721536.json
tests/ci/scripts/post-install-test.sh

Update CI build to run the etl mapping tests.
This change also removes the test artifacts from the build - they
do not belong in the production release.
Also, it appears that the test data has not been updated - this
change also updates the expected results to match the expected
data.

Update CI build to run the etl mapping tests.

---

.circleci/config.yml

This PR fixes the paths to the XML test results in the CircleCI config. Some of the paths were set to `/tmp/phpunit`, and some were set to `~/phpunit`. As a result, the directory `/tmp/phpunit` was created, but the test results were written to `~/phpunit`, which was assumed to be a file rather than a directory, and then CircleCI stored `/tmp/phpunit`, which was empty. This PR sets all of the paths to `~/phpunit` rather than `/tmp/phpunit` to be consistent with the CircleCI config of the `xdmod` repository. It also gives filenames to each of the tests that use `--log-junit` so that the results are saved to files rather than being output to the terminal.
I checked the `build-fresh_install-rocky8` and `build-upgrade-rocky8` checks to make sure the test results show up in the "TESTS" tab, …

Fix CircleCI test result paths.

---

tests/regression/lib/Rest/WarehouseRawDataSupremmTest.php

This PR fixes intermittent failures of the raw data regression test. The failures are due to the fact that for the `fresh_install` test mode, the mapping of `id` to `name` in the `modw_supremm.exit_status` table is non-deterministic. As a result, requesting the `rest/warehouse/raw-data` endpoint with the `filters[exit_status]` parameter set to specific input values does not always produce the same output rows across multiple CI runs. This PR changes the test to instead filter by `application`, which reliably produces the same output rows due to a deterministic mapping of IDs to application names in `modw.application` across multiple runs.

Fix raw data regression test.

---

.gitignore
NOTICE
assets/setup.sh
composer.json
composer.lock
docs/supremm-notices.md
html/.eslintrc.json
html/gui/lib/package-lock.json
html/gui/lib/package.json
html/internal_dashboard/supremm/js/stats.js
html/internal_dashboard/supremm/stats.php

Builds with the `supremm` module are currently failing on the `composer install` step with error `The "https://github.com/jsplumb/jsplumb/raw/1.6.3/dist/js/jquery.jsPlumb-1.6.3-min.js" file could not be downloaded (HTTP/2 404 )`. This is because the repository containing that file has moved.
This PR fixes this by updating the jsPlumb dependency to the latest version, `6.2.10`.
jpPlumb is now installed via NPM instead of Composer.
This PR also updates the licensing information to specify that the dependency is jsPlumb Community edition and to link to its new GitHub repository containing the licensing information.
This PR also updates the `.eslintrc.json` file in the `html` directory to use ES6 for syntax checking.
I tested installing the module on my port on `xdmod-dev` using the …

Update jsPlumb dependency.

---

classes/DataWarehouse/Query/SUPREMM/JobDataset.php

The same as https://github.com/ubccr/xdmod-xsede/pull/439 but for the `xdmod-supremm` module.
In addition to ensuring the regression tests still pass, I also ran the following steps before https://github.com/ubccr/xdmod-xsede/pull/439 was merged. Now that that PR is merged, the following steps will not produce differences because the changes from that PR are redundant with this one on `xdmod-dev`, since `xdmod-xsede` has a version of the file changed in this PR that overrides this one in `xdmod-supremm`. I'm leaving the steps here for posterity:
1. Run the script from https://github.com/ubccr/xdmod-xsede/pull/436.
1. For the differences in the `SUPREMM` realm:
1. Copy the "only in old" lines into a file (e.g., named `old`), run  `cut -d',' -f1 -f21 old | cut -d"'" -f2 -f4` to get the Job …

Use the portal's time zone for raw data query dates instead of UTC.

---

html/.eslintrc.json
html/gui/js/modules/efficiency/Efficiency.js
html/gui/js/modules/efficiency/FilterPanel.js
html/internal_dashboard/supremm/css/style.css
html/internal_dashboard/supremm/js/stats.js
html/internal_dashboard/supremm/stats.php

Replaces any jQuery calls with native JavaScript. This PR is dependent on the[ base xdmod jQuery PR](https://github.com/ubccr/xdmod/pull/1756). Most of the changes are with the SUPReMM Dataflow diagram displayed in the internal dashboard.
jQuery is a large dependency that we use very sparingly.
Ran tests in docker container and viewed changes on xdmod-dev.

Replace jQuery with native JS

---

.circleci/config.yml

This PR removes the specification of the `xdmod` repo branch since the default branch is what is desired.

Remove specific `xdmod` branch from CircleCI config.

---

.circleci/config.yml
CHANGELOG.md
build.json
docs/_config.yml
docs/supremm-upgrade.md
tests/ci/scripts/install_mongo.sh

This PR prepares the `xdmod11.0` branch for development of version `11.0.1`. It depends on https://github.com/ubccr/xdmod/pull/1939.

Prep for v11.0.1 development.

---

CHANGELOG.md
build.json
docs/_config.yml
xdmod-supremm.spec.in

Port of https://github.com/ubccr/xdmod-supremm/pull/406 for the `main` branch.

Update changelog for 11.0.1.
